### ISSUE TITLE
Build style job is failing with error

### ISSUE THREAD

**Issue by wtrocki** [nodeshift/nodejs-reference-architecture#94]
Checking if module is tested by community CITGM runs              WARN 
TypeError: Cannot read property 'cves' of undefined
    at /home/runner/.npm/_npx/2123/lib/node_modules/npcheck/src/plugins/audit.js:60:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async auditPlugin (/home/runner/.npm/_npx/2123/lib/node_modules/npcheck/src/plugins/audit.js:69:28)
    at async Object.run (/home/runner/.npm/_npx/2123/lib/node_modules/npcheck/src/cli.js:101:24)
Error: Process completed with exit code 1.

**Comment by richardlau** [comment]
>  My guess is that currently, something's going wrong with the `odbc` package.

That package has [pre-requisites](https://github.com/markdirish/node-odbc) to build (e.g. on RHEL/CentOS, `sudo yum install unixODBC unixODBC-devel`)
